language: objective-c
xcode_project: DBNetworkStack+Sourcing.xcodeproj # path to your xcodeproj folder
xcode_scheme: DBNetworkStackSourcing
osx_image: xcode8.3
before_install:
  - export SNAPSHOT_FORCE_DELETE=1
  - fastlane snapshot reset_simulators
install:
  - carthage update --platform ios --no-use-binaries
script: 
- set -o pipefail && xcodebuild -scheme DBNetworkStackSourcing -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' ONLY_ACTIVE_ARCH=NO clean build test -enableCodeCoverage YES | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
